name: Build release

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - run: bundle install

      - name: Build gem
        run: |
          gem build arask
      - name: Upload gem
        uses: actions/upload-artifact@v3
        with:
          name: arask
          path: arask-*.gem
